### ISSUE TITLE
Implement Github Actions

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-elasticsearch#27]
As titled, given the proper Docker support, it would enable us to provision ES better.

**Comment by jsumners** [comment]
I don't know what you mean by "proper Docker support", but if you want to use images from the organization's Docker repository then you have to do some trickery as outlined in https://github.com/ldapjs/node-ldapjs/pull/571

If you just want to pull random images from the public Docker Hub, then it should be doable.

**Comment by mcollina** [comment]
Currently we do some weirdness to run ElasticSearch. Using docker would enable us to avoid flakiness.

**Comment by delvedor** [comment]
I'll take care about this, I need to run some experiments also for [elastic/elasticsearch-js](https://github.com/elastic/elasticsearch-js).

**Comment by Fdawgs** [comment]
@mcollina , can this issue be closed?
Seems the migration to GitHub Actions happened a while ago. 😸

**Comment by delvedor** [comment]
@Fdawgs yes!
