### ISSUE TITLE
Ping cluster

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-elasticsearch#3]
We should validate that the connection was established otherwise the client should exit and come back in a clear state.

```js
client.ping({
  // ping usually has a 3000ms timeout
  requestTimeout: opts.timeout
}, function (error) {
  if (error) {
    fastify.log.error(err, 'elasticsearch cluster is down!')
	// exit server
  } else {
    fastify.log.debug('elasticsearch cluster is available')
  }
});
```

**Comment by StarpTech** [comment]
Do you agree that the server should exit?

**Comment by mcollina** [comment]
I think we should wait that the connection is established before loading the next plugin (calling `next()`). If there is an error, we should error there.

**Comment by StarpTech** [comment]
Solved with https://github.com/fastify/fastify-elasticsearch/pull/4
