### ISSUE TITLE
relase 0.3.0

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-elasticsearch#7]
hey @allevo, I don't have publish right here, would you mind releasing?

**Comment by allevo** [comment]
Good but not so good. How can give you the permissions?

Anyway I'm releasing this now

**Comment by mcollina** [comment]
You can add it to the org now, I've bumped you to admin.

**Comment by mcollina** [comment]
https://www.npmjs.com/org/fastify

**Comment by allevo** [comment]
Done, both
