### ISSUE TITLE
Compatability issue for fastify 4.x

### ISSUE THREAD

**Issue by kaanbisu** [fastify/fastify-elasticsearch#86]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello, 

I have started a project with fastify and fastify-elasticsearch but after installed fastify-elasticsearch i got a version mismatch error, the error is in here:

```js
FastifyError [Error]: fastify-plugin: fastify-elasticsearch - expected '3.x' fastify version, '4.2.1' is installed
    at Object.checkVersion (/.../node_modules/fastify/lib/pluginUtils.js:118:11)
    at Object.registerPlugin (/.../node_modules/fastify/lib/pluginUtils.js:133:16)
    at Boot.override (/.../node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/.../node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/.../node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}
```

The versions i used:
```
NodeJS v16.15.1
Fastify v4.2.1
Fastify-elasticsearch v2.1.0
```
Tested on MacOS Monterey (12.4) w/ MBP 2019.

**Comment by Eomm** [comment]
You need to install `@fastify/elasticseach` https://www.npmjs.com/package/@fastify/elasticsearch

> Fastify-elasticsearch v2.1.0

that version does not exist https://www.npmjs.com/package/fastify-elasticsearch

**Comment by mihaur** [comment]
Latest release @fastify/elasticseach@v2.1.0 (Apr-27) uses fastify-plugin@3.0.0 which gives the above error - https://github.com/fastify/fastify-elasticsearch/blob/v2.1.0/package.json

Version on master uses fastify-plugin@4.0.0 and works with fastify4. Please make a new release.

**Comment by mcollina** [comment]
This module has not been updated to Fastify v4 yet. It's blocked on https://github.com/fastify/fastify-elasticsearch/issues/78. If you would like to help it would be amazing.

**Comment by mihaur** [comment]
I have submitted a PR. CI is waiting for approval.
